### ISSUE TITLE
Why did this post get scanned multiple times?

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/flovis-farmhouse#4]
https://flovis.charcoal-se.org/posts/13170

![image](https://user-images.githubusercontent.com/6462439/40991352-288420c2-68b9-11e8-9426-011009150513.png)

This post is shown as being received twice, enqueued twice and getting "not_spam" three times. Why?

**Comment by ArtOfCode-** [comment]
Simple answer: because it was.

Longer answer: that post was updated after initial submission, which caused it to be sent via the realtime socket to Smokey again. The third not spam is down to the post getting returned in another API call without coming down the socket - I believe we call for recent posts on SO via the API to make up for the fact that they don't all go down the websocket, so that's likely where it's from.
